### ISSUE TITLE
Elite Syndicate Hardsuit does not seem to be pressurized

### ISSUE THREAD

**Issue by KoboldCommando** [Monkestation/MonkeStation#102]
I bought the elite syndicate hardsuit.  Was wearing it with a syndicate mask.  And was taking temperature and pressure damage outside (I was inside a mech if that makes a difference)

**Comment by nednaZ** [comment]
Elite Hardsuits are pressurized IF in EVA mode.
You need to hit the "Toggle Helmet Mode" button
