### ISSUE TITLE
You can use the scope of the sniper without holding it

### ISSUE THREAD

**Issue by KoboldCommando** [Monkestation/MonkeStation#107]
During the setup of the nukie round tonight:
[Syndicate] George Carr says, "I CAN USE THE SCOPE OF MY SNIPER WHILE IM NOT HOLDING IT."

**Comment by nednaZ** [comment]
Can't seem to replicate this one.
Putting the gun away, dropping it, throwing it or any other actions will drop you out of sniper vision.

The only exception I see is holding the rifle in one hand and using the scope with the other, but that still requires it to be held.

**Comment by nednaZ** [comment]
Could never replicate, likely non-issue.
