### ISSUE TITLE
Atmos Helm Broken

### ISSUE THREAD

**Issue by IronGoddess54** [Monkestation/MonkeStation#109]
Atmos helm refuses to be equipped. Is held then when equipped to head it is dropped. On the floor in the interaction menu its sprite is broken.

**Comment by nednaZ** [comment]
How were you attempting to equip it?
Was this the hardsuit version or the firesuit?
If this was the hardsuit, did you press the "Toggle Helmet" ability button?

**Comment by nednaZ** [comment]
Should be fixed by #139 if this was the issue I believe it was.
