### ISSUE TITLE
Hold alt for strafing as mech doesn't work

### ISSUE THREAD

**Issue by KoboldCommando** [Monkestation/MonkeStation#110]
I was struggling with a mech last night.  Holding alt + WASD to strafe was not working.  And switching to strafe mode then holding alt + WASD to turn was not working either.  Couldn't figure out what was wrong.

**Comment by nednaZ** [comment]
Yeah. Looks like alt-strafe is broken.

**Comment by nednaZ** [comment]
Issue known upstream:
https://github.com/BeeStation/BeeStation-Hornet/issues/6308

**Comment by KoboldCommando** [comment]
This is still broken, and the upstream issues appear to be stale and unaddressed.

This applies to walk mode as well, if you hold alt you will go into walk mode, but the game doesn't recognize you then pressing WASD as actually trying to move in those directions anymore.

Something seems to have changed with how hotkeys with modifiers are handled in general, and it's a big mess.

**Comment by KoboldCommando** [comment]
This was reported again today.  ctrl+WASD causes you to freeze in place, even if you unbind "face direction".  The bug is still at large and very impactful in some areas of the game.

**Comment by nednaZ** [comment]
Unfortunately there seems to be zero solution for this.
/tg/ knows about it, Bee knows about it, but nobody has given any possible cause or solution.
