### ISSUE TITLE
E to auto stash/equip items is all borked up

### ISSUE THREAD

**Issue by KoboldCommando** [Monkestation/MonkeStation#111]
I'm not sure what's wrong with it, but the keybind where you pick up an item and press e to automatically put it in your inventory is SUPER messed up.

Expected: I pick up an item and hit E, it should go into an appropriate equipment slot, or if there are none, into my pocket, or if those are full, into the current open container, or otherwise into my backpack.

Experience: I picked up an item and hit E, and an item in my pocket was swapped into my hand, and the held item was placed into that pocket.

I also picked up some wirecutters, with my toolbelt open and empty, and hitting E placed them into my backpack instead.

**Comment by nednaZ** [comment]
This looks like a quick-swap hotkey issue. Something is acting up there and the original hotkey isn't working...again.

**Comment by polygoblyn** [comment]
alrighty I've figured out both problems.  First: I had ITEM_SLOT_BACK twice, instead of ITEM_SLOT_BELT.  Second,  I had Alt+E intead of Alt-E
