### ISSUE TITLE
Metastation toxins airlock never cycles

### ISSUE THREAD

**Issue by pitaden** [Monkestation/MonkeStation#121]
According to Thrumbo, the dual-port vent never actually turns on if you click cycle to exterior, permanently bolting the doors until you hack out.

From a bit of testing, it seems like the issue is with the dual-port vent itself, not the way the pipes are laid out

**Comment by pitaden** [comment]
Issue isn't limited to toxins, happens with the incinerator too.

**Comment by nednaZ** [comment]
Incinerator part fixed by #272
