### ISSUE TITLE
Blood on items sprite mess up

### ISSUE THREAD

**Issue by WonderPsycho** [Monkestation/MonkeStation#138]
so apparently according to info i got this blood sprite mess up is apparently a thing that's happening in all of bee code in general instead of just our code base, what the bug is, that the sprites for blood on items is all messed up in mainly any and all of bee code forks and regular bee code, hopefully we will find a fix for this or bee will find out a fix for this soon

**Comment by nednaZ** [comment]
https://cdn.discordapp.com/attachments/941883395997331510/942719260973731910/FUCKEDUPBLOODSPRITES.PNG

Adding the image you posted as well.

**Comment by WonderPsycho** [comment]
> https://cdn.discordapp.com/attachments/941883395997331510/942719260973731910/FUCKEDUPBLOODSPRITES.PNG
> 
> Adding the image you posted as well.

thanks
