### ISSUE TITLE
Fanny issues

### ISSUE THREAD

**Issue by polygoblyn** [Monkestation/MonkeStation#148]
Some bugs I noticed:

When laying down, you can fart on someone's face who is standing up.  You also get two messages in this case, one for the normal fart emote and one for the targeted farting emote.

Conversely when standing and farting on someone, others do not see your fart emote at all.

**Comment by nednaZ** [comment]
To add to this with issues I've seen:
Atomic Asses do not reset for use after they detonate.

**Comment by lmenvs** [comment]
Looks like the fixed targeted farting still does not show for others.  I wish to humiliate my victims!!
