### ISSUE TITLE
The HoS gun is... weird.

### ISSUE THREAD

**Issue by KoboldCommando** [Monkestation/MonkeStation#154]
Some things I've noticed include the gun (fully charged) clicking as if I tried to fire it when I go to put it in my backpack.  And attacking my backpack with it as if I'm hitting a table with a crowbar when trying to put it in a full backpack.  Something is very odd about the way it behaves.

**Comment by lmenvs** [comment]
This is because it has force on it.  Seems like a race condition between whether an item's attack() proc or the target's attackby() proc fire first.  Per borbop, "as for a fix i don't really think their is one as its most likely a scheduler fault and not a code fault"
