### ISSUE TITLE
Civilian Bounties show some incorrect (or not?) numbers

### ISSUE THREAD

**Issue by KoboldCommando** [Monkestation/MonkeStation#155]
I took a bounty for a firefighter mech.  It listed it as 5000 credits which seemed a bit low.  I fulfilled it and received an 18,000 credit bounty cube.  When selling this I received 5400 credits to my bank account (the rest going to cargo).

I'm not 100% sure whether this is intended?  If the bounty is supposed to be showing what YOU PERSONALLY get?  It needs investigated and straightened out either way.

In addition, when selling one bounty cube, it once again reports having sold 2 bounty cubes on the cargo console.

**Comment by nednaZ** [comment]
The bounty shows what you will get (pre-bonus), while the cube shows the total amount (pre-bonus).
I think the double cube issue is because it's either giving money to two people OR it's counting the internal radio as a sold item.

**Comment by KoboldCommando** [comment]
The internal radio is properly deleted, it was an issue I had to fix.  It would show up on the report and award you 4 credits.  It may be the way the money is splitting though, that's a good thing to check, thanks!
