### ISSUE TITLE
Invisimin Issues

### ISSUE THREAD

**Issue by nednaZ** [Monkestation/MonkeStation#168]
Going "invismin" seems to only work on the client side.
I've had people immediately see me, or see me through the HUDs.
It also makes you deaf and unable to see emotes or text.

**Comment by WonderPsycho** [comment]
yikes poor invismin option, seems admemes can't go invisible amongst the playerbase and can't see what everyone is doing or saying anymore while doing it

**Comment by Merlin1230** [comment]
To add onto this, the invismin straight doesn't work with ghosts which is the ONE thing I want it to work on. I haven't looked at how invismin works but we could probably just use the invisibility var as an easy way to do it.
