### ISSUE TITLE
Coin shop items can refuse to spawn if you're a stowaway

### ISSUE THREAD

**Issue by KoboldCommando** [Monkestation/MonkeStation#176]
I tried out stowaway.  I was roboticist.  They start wearing a labcoat, and I had bought a winter jacket, so it should spawn in my hand.  I woke up in a crate, and the jacket was nowhere to be seen!  This happened twice.

One time I also had brain tumor, and my bottle of pills DID spawn, but it was on the ground in the crate with me.

**Comment by nednaZ** [comment]
Brain Tumor: Roundstart & Latejoin spawned the bottle on top of the locker.
EXCEPT when using other traits that give items.
Paraplegic: Wheelchair appears on top of the locker.
Junkie: Drugs appear in the backpack.

Likely found the issue, will be able to fix.
