### ISSUE TITLE
CQC doesn't work on monkeys 

### ISSUE THREAD

**Issue by mrKiwiBird** [Monkestation/MonkeStation#198]
as a chef you cant use your CQC on monkeys making it really rough to take them down

to reporduce:
be chef
try to CQC a monkey
cry beacuse you get mauled

**Comment by Merlin1230** [comment]
I think monkeys in general are just weird when it comes to this sorta stuff, I remember trying to use a whip on one to trip it but... it didn't work

**Comment by Serxule** [comment]
ah right, its because monkeys here are listed as simplemobs, tg fixed this by having them be subhumans in code

**Comment by dwasint** [comment]
martial arts work against humanoid targets for the most part this includes cqc. Closing as its intended but will be solved when monkeys become a human subtype
