### ISSUE TITLE
Simian sprite bugs

### ISSUE THREAD

**Issue by lmenvs** [Monkestation/MonkeStation#252]
Please post here, with screenshot of  your issue (Shift + win + S to snip a bit of your screen, then paste it in!)

**Comment by nednaZ** [comment]
Space Helmets and Gas Masks are missing sprites.

**Comment by Bedsheet01** [comment]
Adjusted suits do not have sprites for simian race. They just make you naked
Detective's Noir suit does not have a sprite for the simian race
Bowman security headset floats above simian's heads

**Comment by Bedsheet01** [comment]
Amish suit also doesn't work for Simian race

**Comment by Bedsheet01** [comment]
None of the pants clothing does not work for simian's. There is no sprite

**Comment by Serxule** [comment]
(presumably) most costume vendor clothing doesnt have wear sprites

**Comment by Sord213** [comment]
HoP cape missing worn sprites

**Comment by Serxule** [comment]
chaplains armaments, etc, have fucked sprites 
(example) 
![Screenshot_2163](https://user-images.githubusercontent.com/64584757/163087017-bfb07f96-d84a-4bce-87f1-138dc9f805fc.png)

**Comment by lmenvs** [comment]
> chaplains armaments, etc, have fucked sprites (example) ![Screenshot_2163](https://user-images.githubusercontent.com/64584757/163087017-bfb07f96-d84a-4bce-87f1-138dc9f805fc.png)

they are not fucked up, they are just missing the simian version.

**Comment by lmenvs** [comment]
All 'missing' sprites should be replaced with human sprites.  Please report only missing sprites for now
