### ISSUE TITLE
Simian Bugs

### ISSUE THREAD

**Issue by lmenvs** [Monkestation/MonkeStation#253]
Post your stuff here, please be as descriptive as possible

**Comment by lmenvs** [comment]
Foreigners get common in their translators

**Comment by nednaZ** [comment]
Table flipping into a disposals chute doesn't appear to work.
Throws you against the chute to damage it, but doesn't put you inside.

**Comment by nednaZ** [comment]
Simians cannot actually just get onto a table, they always throw themselves.

**Comment by lmenvs** [comment]
> Table flipping into a disposals chute doesn't appear to work. Throws you against the chute to damage it, but doesn't put you inside.

they have the same chance as items

**Comment by KoboldCommando** [comment]
> 

An idea for this: maybe while they're in walk mode they could climb normally!

**Comment by KoboldCommando** [comment]
When you use the translator in hand it gives you a list of languages to choose from.  But it lists them as their datum paths rather than the names.

**Comment by nednaZ** [comment]
Random simians always seem to get Albino coloration

**Comment by nednaZ** [comment]
Balance issue.
The health changes may have made simians a bit too weak.

**Comment by KoboldCommando** [comment]
If you wear two translators, it translates based on the last translator you equipped.

I hope it gets changed so they all translate and you broadcast your voice multiple times, hehe

**Comment by KoboldCommando** [comment]
Buckling into an upward-facing shuttle chair shows me on top of the chair rather than in/under it.

**Comment by nednaZ** [comment]
You can klepto your own implants out.

**Comment by Serxule** [comment]
not much of a bug, but the stunlock after vaulting tables should be removed

**Comment by Serxule** [comment]
simiams also cant climb onto crates, since it throws, like what zanden said

**Comment by Bedsheet01** [comment]
When you use a transformation sting on a simian and then try to transform to them. You will instead become a random normal monkey and will be stuck as said monkey, since it thinks you switched to your primal form (Or whatever the ability is called)

**Comment by nednaZ** [comment]
Simian ERT members do not spawn with their translators

**Comment by lmenvs** [comment]
Simians can now only vault on tables, fixed klepto procs from mechs, limbless pickpocketing, buffed health, klepto chance is now 2.5% and a stored variable for adminnery,

**Comment by lmenvs** [comment]
> 

I've tried to replicate this and can't figure out how you managed to get this to occur, but will keep an eye out on it

**Comment by lmenvs** [comment]
Fixed ERT members and centcom officials
