### ISSUE TITLE
Engineering techfab can't print analyzers

### ISSUE THREAD

**Issue by KoboldCommando** [Monkestation/MonkeStation#254]
You know, those tools atmos needs to do their job?  lol.  Seems like it should be a roundstart printable item without having to hoof it to cargo.

They can print long range analyzers just not the normal ones.  I think the science techfab is the same, though they at least have an autolathe.

**Comment by lmenvs** [comment]
This is in the autolathe

![image](https://user-images.githubusercontent.com/85052537/223929808-3ca02be8-e9a2-4911-8ded-cf74436ed8a8.png)

![image](https://user-images.githubusercontent.com/85052537/223929833-beaa9ff3-f723-40f5-ab74-e6decc089814.png)
