### ISSUE TITLE
A lot of people can't really get to telecoms on metastation

### ISSUE THREAD

**Issue by KoboldCommando** [Monkestation/MonkeStation#255]
For whatever reason the tcomms room on metastation is on the AI satellite, and is behind the first line of AI defensive turrets.  I don't think tcomms is nearly so heavily defended on other stations (it's a simple door on box).  I believe there are some cases where you can have access to the room but no way to actually get there since only a few people have turret access.

Honestly tcomms being so isolated and linked with the AI is one of my biggest gripes about meta overall.

**Comment by Serxule** [comment]
i mean thats exactly why its there, tcomms is incredibly important so it was put somewhere thats heavily protected

**Comment by KoboldCommando** [comment]
As I mentioned, this flies in the face of the design of other maps, and the turrets make it outright impossible for crew members maintain and protect telecomms unless a head or a cooperative AI is around.  Meanwhile on boxstation it's immediately adjacent to engineering, and on pubby it has its own engineering-connected minisat with no turrets.  Crew members are granted access to telecoms (at least on lowpop) and yet have no access to turrets and thus are totally unable to access the department.
