### ISSUE TITLE
UI popup queue conflicts (adminsay in particular)

### ISSUE THREAD

**Issue by KoboldCommando** [Monkestation/MonkeStation#258]
There's some kind of queue when it comes to UI popups, and it causes issues sometimes.  There are some player-side, but the most frequent one I run into is that adminsay is exclusive with a whole lot of menus.  So you're elbow deep in configuring something, and you want to reply to something or ask a question over adminsay, but the F3 key does nothing until you close that menu you're already in.

Finding a way to make some of these menus parallel would be a big QoL improvement!

**Comment by dwasint** [comment]
sadly this seems to be a byond limitation by using inputs nothing we can do without switching to tgui(which we should)
