### ISSUE TITLE
The say window pops up partly over the gameplay, which is annoying for editors

### ISSUE THREAD

**Issue by KoboldCommando** [Monkestation/MonkeStation#259]
This is a super old issue and one most people probably don't even think of.  But I think it's good to bring up since we want to be a server that's friendly toward content creators!  When I've edited SS13 videos a constant thorn in my side has been the "say" popup.  It appears directly front-and-center, which places it halfway over the gameplay view, and halfway over the UI.  It's very hard to comfortably crop and zoom to get rid of it, and leaving it on screen is really distracting and ugly.

If we could nudge it over to the right so it shows up over the UI by default, that would be so nice from a video editor standpoint!

**Comment by lmenvs** [comment]
I looked into if this could be fixed a while ago and without getting tgui say (and I'm not sure that'd entirely resolve it either) it's not really possible
