### ISSUE TITLE
UI popup focus/hotkeys

### ISSUE THREAD

**Issue by KoboldCommando** [Monkestation/MonkeStation#260]
Since I'm making 400 UI issue posts, this is worth adding.  Various UI menus that pop up steal focus.  Which means that your hotkeys are no longer inherited by the base game window.  So you press W to walk away from the clown holding an active bomb?  Nope now your inputs are going directly to the UI that came up.

One of the easiest showcases of the pain is when piloting a mech, if you're trying to manage things in the status menu while also maneuvering.

I'm not sure if there's a clean and easy fix, since often you WANT to intercept those hotkeys before they reach the base game.  But it's definitely an issue and figuring out a way for it to behave more cleanly and intuitively would represent a massive improvement in quality of life.

**Comment by dwasint** [comment]
this is actually a thing already implemented just not for many keys. Will look into this in the future

**Comment by dwasint** [comment]
this is now a setting you can toggle on menus code wise so closing
