### ISSUE TITLE
Something is fucked up with robot pathing

### ISSUE THREAD

**Issue by KoboldCommando** [Monkestation/MonkeStation#262]
I'm not sure what might have happened, or how recently.  But something changed, and robots are behaving differently and oddly.

You can see this by building some small robots on Pubbystation and telling them to patrol.  Last time I had a little conga line of medibots and atmos bots pacing about 6 tiles back and forth in front of science.

I've also noticed that all the patrolling robots on metastation now love walking right through the engine room.  Which can be very bad for various reasons.  Beepsky now lets the spicy air out and the insul-seeking assistants in, damn him.

Mulebots are, as usual, finding their paths less and less consistently.  But they need a full overhaul to themselves.

**Comment by Serxule** [comment]
honestly robot pathing is always super fucking weird and unless it gets reworked i dont think there's much to do
