### ISSUE TITLE
BYOND Member Color doesn't save across rounds

### ISSUE THREAD

**Issue by unit0016** [Monkestation/MonkeStation#301]
See title. OOC Preferences, BYOND Membership Color doesn't save.
Wack.

**Comment by Xkeeper0** [comment]
Can't reproduce. There was an issue where setting it to too bright of a color would cause it to save a reduced-brightness version, but so far it is saving my OOC color (as a BYOND member) as expected

**Comment by unit0016** [comment]
> Can't reproduce. There was an issue where setting it to too bright of a color would cause it to save a reduced-brightness version, but so far it is saving my OOC color (as a BYOND member) as expected

Continue to be able to reproduce. Exact color chosen was dead right of white, palest pink. Hex code isn't on hand at the moment.

**Comment by Xkeeper0** [comment]
Try choosing a darker color. I use `#00FF00` and it work as expected
