### ISSUE TITLE
Plasma does not create sustained burn in oxygen rich enviroment.

### ISSUE THREAD

**Issue by williamcll** [Monkestation/MonkeStation#305]
Round ID: 653
under normal circumstances, Plasma would easily ignite under an oxygen rich environment, producing tritium. However on this round, neither atmospherics nor toxins could get a trit reaction going. Turning on the igniter simply creates a small fire the extinguishes momentarily.

**Comment by Serxule** [comment]
this isnt a bug, i have no problems with making tritium

**Comment by williamcll** [comment]
> this isnt a bug, i have no problems with making tritium

seemed to be a one-time issue, I do not know what triggered it either.
