### ISSUE TITLE
Rare "alien_artifact.dm null.invoke runtime" that prevents a debug from running

### ISSUE THREAD

**Issue by DoctorSquishy** [Monkestation/MonkeStation#340]
"alien_artifact.dm null.invoke runtime" This runtime happens on `/atom/movable/proximity_monitor_holder/HasProximity(atom/movable/AM)` and I actually can't skip it when it happens, so I have to restart the debug game launch.

[code/modules/shuttle/super_cruise/orbital_poi_generator/loot/alien_artifact.dm](https://github.com/Monkestation/MonkeStation/blob/5769ccdc0eebe7ef2bfadb11bd604bddb1ecef85/code/modules/shuttle/super_cruise/orbital_poi_generator/loot/alien_artifact.dm)

```DM
//===================
// Projectile Reflector
//===================

/atom/movable/proximity_monitor_holder
    var/datum/proximity_monitor/monitor
    var/datum/callback/callback

/atom/movable/proximity_monitor_holder/Initialize(mapload, datum/proximity_monitor/_monitor, datum/callback/_callback)
    monitor = _monitor
    callback = _callback
    monitor?.hasprox_receiver = src

/atom/movable/proximity_monitor_holder/HasProximity(atom/movable/AM)
    return callback.Invoke(AM) //Runtime issue?
```

I am wondering if changing:
```DM
/atom/movable/proximity_monitor_holder/HasProximity(atom/movable/AM)
    return callback.Invoke(AM)
```
To this:
```DM
/atom/movable/proximity_monitor_holder/HasProximity(atom/movable/AM)
	if(callback)
		return callback.Invoke(AM)
```
Would this fix the issue? But I do not fully understand this area of the code to well, so far with it implemented I haven't got the runtime error; however, it is a rare runtime. Probably something to do with the loot spawning sometimes.

**Comment by dwasint** [comment]
no idea what was changed but this runtime has vanished in recent times on local testing going to close until it reappears
