### ISSUE TITLE
Permanently Blurry Screen

### ISSUE THREAD

**Issue by unit0016** [Monkestation/MonkeStation#345]
Issue reported from  Round ID: 781 (Monkestation)

Reporting client version: 514.1583

Iunno what caused this one. Came back from SSD - radstorm got me at some point, and after a series of troubleshooting, I fixed my brain, eyes, mutations - but not one of 'em stopped my screen from being completely blurry, aside from HUD elements and runechat. Vague, weird. But it's what happened.

**Comment by dwasint** [comment]
fixed with planes/layering changes
