### ISSUE TITLE
Pointing a gun at someone forces THEM into a radial menu.  This is bad.

### ISSUE THREAD

**Issue by KoboldCommando** [Monkestation/MonkeStation#365]
It seems the bee implementation of holding someone up with a gun forces the target to show a radial menu letting you choose whether to surrender.  What this means is that somebody can point a gun at you and force you into a radial menu.  Which limits certain actions and can easily result in a misclick, which can be incredibly disastrous if you click surrender.

I don't know who thought this was a good idea.  It makes holdups effectively weaponized menus and UI jank.  It's a terrible idea and needs to be fixed in one way or another.

**Comment by dwasint** [comment]
i think radials are better than the alternative, and makes for a great rp reason, we might need to change a few things about hold ups though
