### ISSUE TITLE
Sometimes Exploration Mission locations don't generate correctly

### ISSUE THREAD

**Issue by spiderhandsmcgee** [Monkestation/MonkeStation#413]
experienced on round 1025, and another round previous to this i dont remember the ID
as per title, sometimes exploration missions will generate the blackbox out in space, sometimes to the point that it's out of bounds for players and requires admin intervention to acquire. This shouldn't be happening, I'm pretty sure.

**Comment by nednaZ** [comment]
That is actually caused by the backup generation method on failed mission generation.
It will place the objective randomly just so you do get an objective, prior to this you would simply have a broken mission entirely.
