### ISSUE TITLE
power randomly drops to 0

### ISSUE THREAD

**Issue by williamcll** [Monkestation/MonkeStation#448]
Round ID: 1097
Pull Requests that are test merged:
[#344: 'Ports Skyrats Liquid System [TM FIRST]' by dwasint at commit 0929246fb5](https://www.github.com/monkestation/monkestation/pull/344)
[#302: 'RBMK Reactor [READY]' by DoctorSquishy at commit 1ecde64716](https://www.github.com/monkestation/monkestation/pull/302)
[#427: 'Fixes Custom Vendor and some oversights on smoothing' by dwasint at commit 8f4e4e869d](https://www.github.com/monkestation/monkestation/pull/427)
Issue:  This round had a nominal operating RBMK of 65% as well as wired solars which provided the station about 720kWs of power, however, according to the power monitor it would randomly drop to 0
![image](https://user-images.githubusercontent.com/43061493/172430838-b41b9da4-9bee-4128-b83f-31c19d018e67.png)

**Comment by dwasint** [comment]
seems to have been fixed or a one off issue as it hasn't come back since
