### ISSUE TITLE
Moved away from another crew member

### ISSUE THREAD

**Issue by NanoCats** [Monkestation/MonkeStation#534]
![image](https://user-images.githubusercontent.com/14065903/178193107-fe1a3430-1008-4b9e-b4c0-2d9320e4cf8b.png)
Handed an atmos tech my PDA to show how slow it was to download a program, and he gave it back, consequently it proceeded to spam my log until an admin deleted and respawned me.

**Comment by dwasint** [comment]
gravity rework should have fixed this closing now
