### ISSUE TITLE
strange bug with end of round report

### ISSUE THREAD

**Issue by etherware-novice** [Monkestation/MonkeStation#574]
so i was in a very low pop round and a florida man spawned in and got on the shuttle, report read above 100% evac rate im not sure if this is intentiona

![bug](https://user-images.githubusercontent.com/73374039/179418486-60b89855-0590-46a7-9720-4e7d4000f5d9.png)

**Comment by etherware-novice** [comment]
also i believe if you get off the shuttle before the actual round end is triggered it doesnt read as escaping on the shuttle everyone was on shuttle

**Comment by nednaZ** [comment]
3 population (crew) + 1 Florida Man.
Numbers add up, seems fine.
