### ISSUE TITLE
Rapid Shuttle Designator Doesn't work.

### ISSUE THREAD

**Issue by unit0016** [Monkestation/MonkeStation#604]
Issue reported from  Round ID: 1577 (Monkestation)

Reporting client version: 514.1585

Tried as a golem. in lavaland. no worky. Go to space to try again. No worky.

**Comment by Xkeeper0** [comment]
Confirming that this is a bug, causes a runtime when you use the RSD:

```
[19:03:52] Runtime in zclear.dm, line 316: pick() from empty list
```

Looks like at least one issue is due to using the wrong check for an empty list condition
