### ISSUE TITLE
Airlocks For All!

### ISSUE THREAD

**Issue by HappiestPlane** [Monkestation/MonkeStation#643]
Issue reported from  Round ID: 1669 (Monkestation)

Reporting client version: 514.1583

So uh. If you left click on any airlock (At least on Metastation) the door opens. Even without ID equipped. Even with an ID with the wrong access. I noticed this a few rounds ago, but thought I may just have access. I was wrong.

If you walk into a door, it responds based on appropriate access. If you click it, though, it WILL open. No matter what. No matter who you are. It WILL open.

**Comment by nednaZ** [comment]
Issue was found and fixed
