### ISSUE TITLE
Can't hit people with pugs (and presumably any other animals)

### ISSUE THREAD

**Issue by Nova-Hero** [Monkestation/MonkeStation#687]
**To Reproduce:**

1. Grab Pugsley IV
2. Use harm intent
3. Hit an object
4. Smile at the faint pug overlaying on the object
5. Try to hit your friend/enemy/clone
6. Cry yourself to sleep as you can not do the funny pug hitting

**Expected Behaviour:**

To be able to hit people with a pug, at least akin to hitting objects

Issue reported from  Round ID: 1778 (Monkestation)

Reporting client version: 514.1585

Sent from my Iphone

**Comment by dwasint** [comment]
animal holders have 0 force so this is intended code wise
