### ISSUE TITLE
The tesla can be hit with the singularity collapser and unaffected

### ISSUE THREAD

**Issue by KoboldCommando** [Monkestation/MonkeStation#749]
In round 1961, 9/23/22, on Stream from Ook, there was a loose tesla and a malf AI.  Someone shot the tesla ball with the singularity collapser, and it made the noise, then it kind of turned around and started bumbling around the ruins of the engine room and stopped destroying stuff, but it didn't disappear.

**Comment by dwasint** [comment]
this appears to be fixed now? going to close for now if it appears in the future it will be reopened
