### ISSUE TITLE
The trash room tube on boxstation will throw people into the wall or even backwards, getting them stuck

### ISSUE THREAD

**Issue by KoboldCommando** [Monkestation/MonkeStation#750]
I saved some poor soul tonight who had been throw in disposals on boxstation.  They were trapped in a tiny 2x1 room behind the outlet where trash falls into the mail room.  He had been thrown backwards rather than into the mail room.

This is not an issue unique to the boxstation remaster.  I've witnessed it many times on box in the past, usually people land inside the wall but sometimes they can be pushed back into this tiny featureless room where they're trapped.  I believe it may happen on some other maps as well.

**Comment by nednaZ** [comment]
I believe the cause of this is because if you hold a movement key while you're about to be ejected from a chute, you can break the pipe.
If you're holding A/Left, that's an instant trapping in that loot room
