### ISSUE TITLE
Liquids sometimes have no name

### ISSUE THREAD

**Issue by KoboldCommando** [Monkestation/MonkeStation#780]
I've seen this a couple times before.  I just came across this liquid, it's supposedly stabilizing agent but by examining it you see nothing.  From the view variables it would seem the reagent list still has the reagent but "reagents" doesn't have it somehow.

![image](https://user-images.githubusercontent.com/31165061/195471434-9ae2a9bd-ecc2-4256-9fd0-1b8bb0613fcb.png)

**Comment by dwasint** [comment]
fixed with liquids group pr
