### ISSUE TITLE
The medbay-adjacent "commissary" has its access set to surgery

### ISSUE THREAD

**Issue by KoboldCommando** [Monkestation/MonkeStation#781]
These two doors and this button have their access set to 45, which is the same as the surgery room.  Maintenance doors are 12, the medbay doors (like to the right) are 5, the commissary access is something else entirely.  This seems really out of place given the morgue surgery was entirely removed and those rooms are basically static maint rooms now.  It's an obvious spot for a shop except for the access issue.

![image](https://user-images.githubusercontent.com/31165061/195472645-3243bd40-e442-48c1-b24e-d95b4aa49ced.png)

**Comment by nednaZ** [comment]
Should be fixed with the latest Box patch.
