### ISSUE TITLE
Hilbert's Hotel impossible to leave without admins

### ISSUE THREAD

**Issue by jamilnielsen** [Monkestation/MonkeStation#820]
in two different instances when using hilbert hotel i could get in, but the door would be bugged requiring admin help to fix.

**Comment by nednaZ** [comment]
Unable to replicate. I need more instructions on how to replicate this issue.

**Comment by jamilnielsen** [comment]
sorry for the late reply, i simply used hilbert's hotel (gained though exploration after breaking display case, took it back to station and used it in the middle of the hallway, the instant i got in the exit had the animation that indicates exit is "broken" aka tiny lightning.
so people could enter, but not leave.
in both instances i had admins to get me out, since you cannot replicate it i will give it an other go when i get around to it and record it if possible.
not sure what else to say, i just pressed Z i believe while holding it, instantly gets teleported inside and thats that, no clue what happens on the outside.

**Comment by jamilnielsen** [comment]
i have send a video on discord, but i'll put it here as well.
this is how its triggered from user's perspective, don't mind the background audio(was watching stream)
https://www.youtube.com/watch?v=uzEwkwhKmgw
