### ISSUE TITLE
Ashwalker finger restrictions not tied to arms.

### ISSUE THREAD

**Issue by jamilnielsen** [Monkestation/MonkeStation#892]
as title, replacing arms does not remove restriction.
makes sense for balance? i dunno.
roleplay? no.

**Comment by MilkForever** [comment]
This also applies to abductors since they can't use guns either.

**Comment by dwasint** [comment]
its a brain trait. designed so ash walkers can't go station side super easy with the bodies they spawn with for now this will stay.
