### ISSUE TITLE
The florida man is able to push the shuttle console

### ISSUE THREAD

**Issue by laOO122** [Monkestation/MonkeStation#893]
Issue reported from  Round ID: 2690 (Monkestation)

Reporting client version: 514.1589

While in use of one of the abilities the florida man can push the shuttle console off the shuttle which could pose a threat to antagonists needing to hijack the shuttle

**Comment by lmenvs** [comment]
Florida man is meant to cause chaos, this seems like a pretty chaotic thing for him to be able to do.
