### ISSUE TITLE
minor ghost model issue.

### ISSUE THREAD

**Issue by jamilnielsen** [Monkestation/MonkeStation#907]
noticed the visibility of my ghost was freaking out, so i figured i would dump it here as a video.
https://youtu.be/NrIneHXMMms
how did it happen? no clue, and ones i started warping around again it disapeared.
reason i posted it here is more that it could be a symtom of something.

**Comment by jamilnielsen** [comment]
this has also happend with non-ghost models, weird.

**Comment by dwasint** [comment]
this is very likely a byond issue itself. Will keep open for now just in case however

**Comment by dwasint** [comment]
looking farther this is a byond issue closing
