### ISSUE TITLE
Warp Whistle perma no movement softlock issue

### ISSUE THREAD

**Issue by WonderPsycho** [Monkestation/MonkeStation#918]
found out of this sort of softlock bug with player characters as wizard or whatever while testing stuff in a private monkestation server i hosted to test stuff related to PRs i am working on and etc, and when i tested the wizard item the "Warp Whistle" apparently after using it and being teleported somewhere else with it, it suddenly just perma softlocks me into losing my movement permanently and I am not sure if this is a issue that happens with other players who tried out the Warp Whistle item in code, but so far from what I can see this issue happens everytime with me when i use that item and i have a feeling it may happen with everytime someone else uses this item, so i decided to submit this issue to notify about this issue being a thing with the Warp Whistle item

**Comment by dwasint** [comment]
looking into it most likely due to update mobility getting removed

**Comment by WonderPsycho** [comment]
> looking into it most likely due to update mobility getting removed

probably and makes sense

**Comment by dwasint** [comment]
fixed by #960
