### ISSUE TITLE
cowboy sec hats eat lights

### ISSUE THREAD

**Issue by lmenvs** [Monkestation/MonkeStation#98]

**Comment by nednaZ** [comment]
Sec officers don't start with disablers

**Comment by pitaden** [comment]
I thought they normally didn't start with disablers on beecode?

**Comment by polygoblyn** [comment]
I have not edited their loadout other than the hats/dusters, that might be something we can consider.

**Comment by nednaZ** [comment]
Beecode does have roundstart disablers in the suit slot.

`suit_store = /obj/item/gun/energy/disabler`

**Comment by nednaZ** [comment]
The issue appears to be that the duster cannot hold the disabler like a normal armor suit

**Comment by lmenvs** [comment]
added states for camera/flashlight
